### ISSUE TITLE
Verrou pour ressources privées

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#129]
Est ce que l'on pourrait afficher un petit verrou devant les ressources privées ?
ex. https://pangloss.cnrs.fr/v2/corpus/Tib%C3%A9tain%20de%20l'Amdo

**Comment by alexis-michaud** [comment]
@sguillaume pourrais-tu nous indiquer quelles sont les ressources concernées ?

**Comment by sguillaume** [comment]
Toutes les ressources privées ont le champs access_right (dans la BDD) égal à 1 !
(dans les tables primary_resources et secondary_resources)

- ressources publiques : valeur d'access_right = 0
- ressources privées : valeur d'access_right = 1

**Comment by alexis-michaud** [comment]
Pour l'instant, les ressources en privé ne s'affichent pas du tout dans l'interface Pangloss, n'est-ce pas ?

Au risque de compliquer les choses : est-ce qu'il serait envisageable de garder comme ça pour la version grand public (pas la peine de mettre sous le nez des visiteurs des ressources qui leur sont fermées), et d'afficher les ressources privées (avec un verrou) dans la liste de ressources en mode PRO ?

**Comment by EdouardSombie** [comment]
Salut,
Jusqu'à présent, il n'y a pas de distinction faite à partir du champ access_right.
Si certaines ressources n'apparaissent pas c'est qu'elles ne font pas référence au bon nom de langue, dans le champ subject.
Pour illustrer cela, vous pouvez regarder les ressources de l'Ouldémé : il y a une ressource publique (id 660) qui fait référence au sujet "[{"code": "udl", "name": "**Ouldeme**"}]" 
alors que les autres font référence à "[{"code": "udl", "name": "**ouldémé**"}]"

Si on regarde dans la table des corpus, cette langue est répertoriée comme suit :
{
    "en": "Ouldeme",
    "fr": "ouldémé",
    "corpus": "**Ouldeme**"
}

**Comment by EdouardSombie** [comment]
Les ressources privées ne s'affichent plus que pour les pros.
Un petit verrou apparait sous le type de ressource pour le ressources privées.
Vous pouvez voir ce que cela donne pour la langue rakhine.
Pour les ressources qui ne s'affichent toujours pas, il faut aller régler le souci en base de données (cf ticket précédent) pour qu'elles fassent référence au bon nom de corpus.

**Comment by sguillaume** [comment]
Il faudrait afficher les ressources privées meme pour le mode grand public parce que pour le rakhine par exemple ça affiche qu'il y a un corpus mais la page est vide car les ressources sont toutes en accès privé.
Ca fait bizarre car on a l'impression qu'il y a un bug.
Mieux vaut afficher toutes les ressources dans tous les modes pour éviter ce genre de cas je pense.

**Comment by alexis-michaud** [comment]
Euh, sauf vot' respect @sguillaume, afficher des ressources privées en mode grand public, ça entre en conflit assez frontal avec l'invitation : venez voir cettet collection en #AccèsOuvert, tout en ligne, #ScienceOuverte, données de la recherche en libre accès --> voyons voir le corpus --> ah ben non c'est privé en fait. 

Pourrait-on explorer d'autres solutions ? 

Dans un premier temps, pour les corpus qui ont zéro données en accès ouvert : ajouter une mention bien visible dans le texte de présentation du corpus (en français et en anglais) pour expliquer que pour telle ou telle raison les données sont en privé. Si possible, fournir l'info sur comment y avoir accès, si un accès est possible (conditions posées par la personne qui a déposé). 

Sans décourager les collègues qui souhaiteraient déposer un corpus en mode "tout privé", ça paraîtrait une bonne chose de prier les dépositaires de corpus "tout en privé" d'envisager de permettre l'accès à au moins une ressource, à titre d'échantillon, non ? Une ressource ou zéro ressource, c'est une différence assez immense.

Une solution plus radicale (et sûrement plus compliquée informatiquement) consisterait à ne pas afficher du tout dans l'interface grand public les corpus dont aucune ressource n'est publique.

**Comment by EdouardSombie** [comment]
Je vous laisse vous mettre d'accord :)

**Comment by sguillaume** [comment]
Ca ne m'aurait pas choqué et j'aurais même trouvé ça intéressant d'indiquer au grand public que parfois certaines ressources doivent (pour protéger la vie privé des gens) rester en mode privé pour une durée déterminée.

Mais pour moi aucun problème qu'on cache ces ressources au grand public si c'est si important.
Le tout est que la page ne donne pas l'impression qu'il y a un bug.

Alexis, cacher les ressources et indiquer que des ressources sont dispos mais en privé revient au même que de montrer les ressources avec un verrou et d'indiquer qu'elle sont en mode privé.

Si tu ne veux pas qu'on voit qu'il y a des ressources privées alors il ne faut plus afficher cette page langue au grand public si aucune ressource n'est disponible.

Une autre idée ?

**Comment by EdouardSombie** [comment]
Petite remarque : 
N'afficher au grand public que les corpus ayant au moins une ressource publique va demander pas mal de travail et de ressources processeur...
Du coup, je penche plutôt pour la solution de Séverine :)
J'attends votre arbitrage !!
