### ISSUE TITLE
Liste des langues présentées aussi par familles de langues ?

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#135]
Demande d'un utilisateur : 
"Liste des corpus: En tant que linguiste, je souhaite qu'il y ait aussi la liste selon les familles de langues. 
"

**Comment by alexis-michaud** [comment]
Demande légitime et naturelle, c'est plus en adéquation avec les préoccupations des linguistes que le découpage par pays, par exemple.
A-t-on l'info pour toutes les langues ? Si oui, c'est peut-être un effort supplémentaire qu'il vaudrait la peine de faire dès la v2 ? @sguillaume @EdouardSombie

**Comment by alexis-michaud** [comment]
On peut passer ça pour le projet de version 3, à quelque temps d'ici. 

Pourquoi pas voir ça de façon un peu ambitieuse : 

- en consolidant l'adossement à des référentiels des infos concernant les familles et sous-familles de langues. L'utilisation de Glottolog et Ethnologue offre le potentiel de faire référence à plusieurs niveaux de regroupements, des familles de langues (groupement le plus élevé) jusqu'au niveau des groupes dialectaux (groupements de 'bas niveau')
- en enrichissant les métadonnées Pangloss / Cocoon pour les corpus qui ne disposeraient pas encore de l'info, et en faisant des mises à jour lorsque c'est nécessaire
- en coordonnant cet affichage avec celui de partenaires qui organisent des collections autour de référentiels concernant les langues : INALCO / BULAC, notamment
