### ISSUE TITLE
Problème affichage liste noms de chercheurs dans la page corpus

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#174]
Comment fonctionne l'affichage de la liste des noms de chercheurs qui ont participé à un corpus ?
Il s'agit de l'affichage des noms de chercheurs qui sont sur la droite de l'affichage des ressources.
Quand on compare aux noms de chercheurs qui apparaissent pour chaque ressources, on voit que cela ne correspond pas toujours.

Exemple : 

https://pangloss.cnrs.fr/corpus/Dotyal -> il manque 3 chercheurs dans la partie droite (Gaborieau, Marc - Helffer, Mireille et Bordes, Rémy)

https://pangloss.cnrs.fr/corpus/Japhug -> là tout est ok (il n'y a qu'un chercheur)

https://pangloss.cnrs.fr/corpus/Abzakh -> là il y a une personne en trop (Batouka, Niaz n'est pas déclaré chercheur dans les métadonnées)

**Comment by EdouardSombie** [comment]
Salut,
L'affichage se base directement sur un champ 'researchers' de la table corpus.
Par exemple, voici le contenu de ce champ pour le corpus Abzakh (il y a bien le chercheur en trop) :

[
    {
        "id": "",
        "name": {
            "en": "Batouka, Niaz",
            "fr": "Batouka, Niaz"
        }
    },
    {
        "id": "",
        "name": {
            "en": "Gsell, René",
            "fr": "Gsell, René"
        }
    },
    {
        "id": "",
        "name": {
            "en": "Konuk, Mezane",
            "fr": "Konuk, Mezane"
        }
    },
    {
        "id": "",
        "name": {
            "en": "Paris, Catherine",
            "fr": "Paris, Catherine"
        }
    }
]

**Comment by EdouardSombie** [comment]
A ce sujet, que pensez-vous de mettre un autre séparateur qu'une virgule entre les chercheurs ?
Car cela peut prêter à confusion, non ?
On peut les mettre à la ligne...

![Capture d’écran 2021-06-08 à 17 49 24](https://user-images.githubusercontent.com/66474742/121217238-f0ba2700-c881-11eb-8e98-3ae5b7861bfc.png)

**Comment by alexis-michaud** [comment]
Oui, un point virgule, ça serait super ! Bien vu.

**Comment by alexis-michaud** [comment]
Bien joué @EdouardSombie ! :+1: 
@sguillaume tu confirmes que c'est bon, le ticket peut être fermé ?

**Comment by EdouardSombie** [comment]
Je confirme !
A bientôt
