### ISSUE TITLE
Bug dans le fil de navigation

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#177]
Lorsque l'on consulte la page des ressources du corpus araki (https://pangloss.cnrs.fr/corpus/Araki), on a 2 versions d'une histoire racontée par la même personne (The oracle of Leruvahi).

La première version est uniquement en araki et tout est ok.

La deuxième version contient 2 langues étudiées (araki et bislama).
La ressource apparait donc dans le corpus araki et dans le corpus bislama (ça c'est ok).

Mais quand on consulte la ressource à partir du corpus araki, au lieu d'indiquer l'araki dans le fil de navigation, c'est le bislama qui est indiqué (https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-57ff574c-4c76-4030-bf57-4c4c76203086&lang=fr&mode=pro) et donc si on remonte d'un cran on se retrouve dans un autre corpus d'une autre langue.

Il faut que lorsque l'on consulte cette version à partir du corpus araki, la ressource reste bien étiquetée comme étant une ressource du corpus araki (et ne donne pas l'impression d'être mal répertoriée) et inversement.

C'est une situation rare (d'avoir 2 langues d'étude dans le même enregistrement et donc une ressource qui doit apparaitre dans 2 corpus différents) mais ça arrive de temps en temps.

**Comment by EdouardSombie** [comment]
Salut, 
On ne peut pas vraiment pas parler d'un bug :)
En réalité, la ressource s'affiche à partir de la première langue à laquelle elle est rattachée dans la base de données.
Du coup, j'ai ajouté un paramètre dans l'url pour que la page affiche le corpus désiré.
Cependant, si ce paramètre n'est pas présent, la ressource s'affichera comme étant rattachée à la première langue en base de données.
A bientôt !

**Comment by alexis-michaud** [comment]
Bien joué @EdouardSombie
