### ISSUE TITLE
souci d'affichage via DOI : alignement <S> seulement à la 2e tentative

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#182]
Souci d'affichage quand on clique sur un DOI qui comprend un ancrage au 1er niveau de granularité. Exemple : 

https://doi.org/10.24397/pangloss-0005673#S37

L'affichage doit se faire en alignant verticalement sur la phrase 37. 

Sur Chrome (sysème Ubuntu) : l'alignement \<S\> se fait seulement à la 2e tentative.
À la première tentative : l'alignement se fait sur le début du document, comme si on n'avait pas passé d'info de numéro de phrase.
Si on [recharge](https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-6cfea344-ef3f-4964-b6ec-871efe6d77df&oai_secondary=cocoon-b976f9db-f0fd-463d-b2d4-7c58366005b9&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr&optionWordTranscriptions=phono&optionWordTranslations=fr&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false) : même souci.
En revanche, si après la première tentative on ouvre le même DOI dans un autre onglet, l'alignement se fait.

Cela rappelle un bogue ancien et résolu : 
https://github.com/CNRS-LACITO/Pangloss/issues/141

**Comment by alexis-michaud** [comment]
@EdouardSombie c'est peut-être pour toi ?

**Comment by EdouardSombie** [comment]
Salut Alexis,
Dans l'url que tu donnes, l'ancre est vers la phrase 37
https://doi.org/10.24397/pangloss-0005673**#S37**

Lorsque je clique sur le lien, j'arrive bien à la phrase 37...
J'ai essayé avec une ancre vers la s9 qui marche aussi.

Du coup, je ne suis pas sûr d'avoir compris le souci :)

**Comment by alexis-michaud** [comment]
Eh oui, si ça n'affecte que ma machine, ça va pas être facile trouver la petite bête. 
Après, Séverine est témoin, donc déjà on sait que si c'est une hallucination, elle est collective :1st_place_medal: :1st_place_medal:

**Comment by alexis-michaud** [comment]
Il semble que ça fonctionne maintenant : même moi je n'arrive plus à renouveler le phénomène. Donc on va fermer le ticket, en restant vigilant concernant le bon fonctionnement du résolveur de DOI.
