### ISSUE TITLE
Affichage d'un groupe de ressources primaires dans 1 même page (notamment : traitement des ressources vidéo et audio liées par dc:relation)

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#184]
Il arrive que des fichiers audio et vidéo soient liés (d'une autre manière que "dcterms:requires" et "dcterms:isrequiredBy" qui concerne principalement les annotations et les EGG).
Le lien est alors juste indiqué par "dc:relation".

Dans ces cas là il faudrait ajouter une règle pour que ces fichiers n'apparaissent pas tous dans la liste des ressources.
Il faudrait que le fichier vidéo apparaisse dans la liste des ressources et que le ou les fichiers audio associés n'apparaissent que dans la page de consultation de la ressource vidéo.
On pourrait voir sur la page de consultation de la vidéo qu'une ou plusieurs ressources audio existent et sont associées à cette vidéo et on pourrait télécharger les fichiers audio ainsi que consulter leurs métadonnées (partie gauche de la consultation de la ressource)

**Comment by alexis-michaud** [comment]
La recherche de pistes continue, y compris une réflexion sur l'encodage des relations dans les métadonnées de Cocoon.

**Comment by alexis-michaud** [comment]
L'enjeu est de bien afficher l'ensemble des ressources liées entre elles / l'ensemble des fichiers qui se rapportent à une même "prise" lors de la captation (enregistrement audio et vidéo fait simultanément + annotations). 

La question concerne 2 niveaux du site : les pages de présentation des corpus (comment présenter la liste des ressources en regroupant celles qui sont liées), et les pages d'affichage des ressources. 

Sur la page de présentation des corpus : regrouper sur une même ligne les ressources liées (comme si c'était la même ressource : c'est des ressources liées). (À l'heure actuelle on a l'audio et la vidéo qui apparaissent sur des lignes séparées). Détecter tous les "dc:relation" (entre ressources primaires) et "dcterms:isrequiredBy".
(Petite note savante : pas besoin d'avoir aussi '"dcterms:requires", le symétrique de "dcterms:isrequiredBy", qui est au fond redondant avec "dcterms:requires".)

Sur la page de consultation d'une ressource, il faut présenter en bon ordre ce "groupe de ressources". 
   
Groupe de ressources primaires qui sont reliées : l'affichage rassemble toutes les ressources reliées "sous lui"
    - sinon si 1 des fichiers est un fichier vidéo il s'affiche et rassemble les autres reliées ressources sous lui
    - sinon si 1 des fichiers est un fichier audio et que l'autre n'est ni un fichier audio (ni un fichier vidéo) alors il s'affiche et rassemble les autres reliées ressources sous lui
       
Question
    - si 2 fichiers sont des fichiers vidéo
    - si 2 fichiers sont des fichiers audio

**Comment by alexis-michaud** [comment]
Affichage : 
onglets en haut (les ressources primaires liées entre elles)
<titre>
DOI
boutons des diverses annotations.

**Comment by sylvainloiseau** [comment]
Si on met le doigt dans la question des relations possibles entre fichiers multimédia et transcription il faut faire un inventaire des situations possibles, de façon à ne pas adopter une solution qui sera mise en difficulté dès le prochain cas de figure.

Parmi les cas de figure il y a par exemple les prises de sons/vidéo en parallèle, le fait qu'un fichier multimédia soit une suite d'un autre (par exemple deux prises de vue), le fait qle fait que certains appareils de captation vidéo découpent en fichier successifs une même prise (pour éviter la limite de taille de 4GO de certains systèmes). Il faut pouvoir préciser quel est le fichier "principal" s'il y en a un et quels sont ceux qui sont "associés", et sans doute préciser ce que veux dire associé ici : une autre prise en parallèle ? un document annexe capturé indépendamment par quelqu'un d'autre et qui apporte un complément de point de vue ; les produits de différents appareils d'enregistrements spécialisés ; Des transformations des données selon certains algorithmes, etc.. Les prises en parallèle peuvent répondre à différentes fonction : audio de qualité pour l'analyse acoustique, vidéo fisheye pour l'analyse d'une interaction, etc.

Je pense qu'un travail d'inventaire des cas de figure pourrait être utile en préalable. De là pourra découler un modèle de données puis une stratégie de visualisation.

**Comment by alexis-michaud** [comment]
En effet, au-delà du premier niveau identifié (rassembler les différentes prises réalisées en même temps), il y a plein de liens possibles entre ressources. 
Pour l'instant, c'est plutôt établi de façon non formalisée informatiquement : par des indications fournies dans le titre des documents concernés, dans la description-résumé qui en est donné...
Par exemple, en langue cuối chăm, il y a 11 documents, qui sont les 11 morceaux d'une même enquête de vocabulaire. C'est dit dans le titre de chacun des documents ("Vocabulaire cuối chăm, partie 1 sur 11", etc), mais il n'y a pas de lien établi au plan informatique entre ces 11 documents. Après, on s'y retrouve tout de même. Il n'y a que ces 11 documents dans le corpus [cuối chăm](https://pangloss.cnrs.fr/corpus/Cu%E1%BB%91i_Ch%C4%83m?lang=fr&mode=pro), de sorte qu'il n'y a pas de risque qu'une personne qui visite le site rate certains documents.

Du coup, pour cette année (2022-2023), avant de mettre en train les 3 étapes que tu proposes (@sylvainloiseau) : _inventaire des cas de figure, modèle de données, stratégie de visualisation_, on va commencer par trouver une solution pour les cas problématiques identifiés. Ce sont des cas où il y a un risque d'induire en erreur la personne qui visite : liste de ressources pas claire, pas intelligible ; et page de consultation "tronquée" qui fait qu'on aborde une ressource "de traviole". Mais rien ne t'interdit en parallèle d'entreprendre une liste des cas de figure (qui aurait toutes chances d'être longue... et sans doute rester ouverte tant la diversité des situations est grande et évolutive avec les technologies). 

PS Pour la petite histoire, voici des liens vers ces documents cuối chăm.
[10.24397/pangloss-0001641](https://doi.org/10.24397/pangloss-0001641)
[10.24397/pangloss-0001642](https://doi.org/10.24397/pangloss-0001642)
[10.24397/pangloss-0001651](https://doi.org/10.24397/pangloss-0001651)
[10.24397/pangloss-0001652](https://doi.org/10.24397/pangloss-0001652)
[10.24397/pangloss-0001653](https://doi.org/10.24397/pangloss-0001653)
[10.24397/pangloss-0001654](https://doi.org/10.24397/pangloss-0001654)
[10.24397/pangloss-0001655](https://doi.org/10.24397/pangloss-0001655)
[10.24397/pangloss-0001656](https://doi.org/10.24397/pangloss-0001656)
[10.24397/pangloss-0001657](https://doi.org/10.24397/pangloss-0001657)
[10.24397/pangloss-0001658](https://doi.org/10.24397/pangloss-0001658)
[10.24397/pangloss-0001659](https://doi.org/10.24397/pangloss-0001659)
[10.24397/pangloss-0001660](https://doi.org/10.24397/pangloss-0001660)
[10.24397/pangloss-0001643](https://doi.org/10.24397/pangloss-0001643)
[10.24397/pangloss-0001661](https://doi.org/10.24397/pangloss-0001661)
[10.24397/pangloss-0001662](https://doi.org/10.24397/pangloss-0001662)
[10.24397/pangloss-0001644](https://doi.org/10.24397/pangloss-0001644)
[10.24397/pangloss-0001645](https://doi.org/10.24397/pangloss-0001645)
[10.24397/pangloss-0001646](https://doi.org/10.24397/pangloss-0001646)
[10.24397/pangloss-0001647](https://doi.org/10.24397/pangloss-0001647)
[10.24397/pangloss-0001648](https://doi.org/10.24397/pangloss-0001648)
[10.24397/pangloss-0001649](https://doi.org/10.24397/pangloss-0001649)
[10.24397/pangloss-0001650](https://doi.org/10.24397/pangloss-0001650)

**Comment by sylvainloiseau** [comment]
Oui lister les cas de figure (prise successives, plusieurs enregistreurs parallèles, plusieurs enregistrements (version) d'un même stimulus, etc.) m'intéresserait bien ; si vous rencontrez des cas nouveaux, je veux bien que vous me montriez. Pour cette année, c'est plus sage en effet de faire une solution simple.

**Comment by sguillaume** [comment]
Edouard, nous ne pouvons pas appliquer la bijection dont nous avons parlé pour les groupes de ressources liées par une "relation".
Parfois 2 ressources peuvent être en relation avec une même ressource sans l'être du tout entre elles.
Il va falloir détecter les groupes de ressources liées par une simple "relation" entre elles autrement.
On en reparle.

**Comment by EdouardSombie** [comment]
Salut Séverine,

Si on ne peut pas déclarer toutes les ressources liées, il va falloir créer une colonne spécifique 'relations' dans notre base de données afin de pouvoir y faire des requêtes récursives.
Toutefois, je me demande s'il ne serait pas mieux de faire cette recherche récursive une bonne fois pour toutes lors de l'import du xml en base de données. On renseignerait alors notre colonne relation…
J'espère juste que cette opération ne va pas trop faire fumer le serveur :)

De toute manière, si on ne peut pas relier ensemble toutes les ressources liées, on va être obligés de faire comme cela.
Est-ce que tu pourrais m'envoyer le xml que tu injectes dans la base de données et me dire quelles ressources primaires sont liées afin que je puisse tester dessus ?

Excellente journée
A bientôt
Edouard

**Comment by sguillaume** [comment]
J'ai peut être une idée. Peut être que l'on peut décider d'afficher les ressources par groupes quand elles suivent une certaine règle et d'afficher les autres séparément ? Mais je ne suis pas sûre que ça sera plus simple car il faudra distinguer les cas.
Après reflexion, je ne sais pas si toutes les personnes qui ont relié leurs ressources avec une simple relation souhaitent forcément qu'elles s'affichent ensemble.
Bon, on en reparle vendredi (peut être que d'ici là on aura une meilleure idée).

En attendant je te mets 2 exemples de ressources liées :

1er exemple (toutes les ressources sont liées entre elles) : 
cocoon-e91226f5-3964-4582-9226-f5396495820c (video)
cocoon-12d5a712-340d-4bd6-95a7-12340dcbd625 (audio)
cocoon-13e01a35-3e04-4747-a01a-353e04c74706 (audio)
cocoon-58c95dc4-e1b2-421e-895d-c4e1b2821e7f (audio)

2ème exemple (les videos sont reliées uniquement à l'audio mais pas entre elle) :
cocoon-c64977f7-e39a-3b1b-87af-27f2daac028c (audio)
cocoon-77a89408-28f2-3313-8a5c-ac4286544507 (video)
cocoon-75aa2208-a754-354e-a28f-e5d44a9afa75 (video)

**Comment by alexis-michaud** [comment]
Pour mémoire, termes proposés pour encoder l'info : 
- dans les métadonnées Cocoon : un champ Dublin Core "`type`" contiendra la valeur : "main" (en français : "principal"), ou "ancillary" (en français : "ancillaire").

Pour une ressource "ancillaire" ("ancillary"), il faudra un champ qui indique l'identifiant de la ressource "main" à laquelle elle se rapporte : son "`main_identifier`". Ce champ contiendra, pour chaque fichier ancillaire, l'identifiant OAI de la ressource principale concernée.

**Comment by sguillaume** [comment]
Proposition : "main resource for the dataset" et "ancillary resource".
Il faut conserver un peu de sens pour que les gens s'y retrouvent.

Validé ?

**Comment by sguillaume** [comment]
Les onglets sont bien présents quand on consulte une ressource faisant partie d’un groupe de ressources liées.
Par contre, les ressources ancillaires continuent d’apparaitre dans la page d’accès aux ressources alors que seules les ressources principales devraient.

un exemple avec le na de yongning :

Il y a 2 ressources liées :

La ressource principale :  https://doi.org/10.24397/pangloss-0004865 (titre : "ComingOfAge3. This is a conversational account, with Bima Lhaco acting as respondent.")

La ressource ancillaire : https://doi.org/10.24397/pangloss-0004866 (titre : Responses of Bima Lhaco (consultant F16) during F4's narrative: “ComingOfAge3”)

Dans chaque page on a bien les ressources regroupées et donc 2 onglets qu’on peut consulter.

Mais ces ressources apparaissent toutes les 2 dans la page d’accès aux ressources (https://pangloss.cnrs.fr/corpus/Yongning_Na?lang=fr&mode=pro) alors que seule la ressource principale devrait apparaitre.

En gros, les ressources ancillaires ne doivent jamais apparaitre dans la page qui liste les ressources d’un corpus.
Elles ne doivent apparaitre que dans un onglet de la page de consultation de la ressources principale.

**Comment by EdouardSombie** [comment]
Salut !
C'est en ligne :)

A bientôt
Edouard
