### ISSUE TITLE
mode PRO : affichage du DOI des annotations

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#193]
Lister les DOI à droite, au bas de la colonne qui contient les liens de téléchargement, les métadonnées...

DOI - Ressource : conserver celui de l'onglet actif

Après DOI - Ressource : ajouter des lignes "DOI - Annotation 1", etc.

**Comment by alexis-michaud** [comment]
@EdouardSombie tu aurais un peu de temps ces semaines-ci pour regarder ? 
Le DOI des annotations t'est-il aisément accessible dans les métadonnées importées dans la base de données de l'interface web ?

**Comment by sguillaume** [comment]
Oui, tous les DOIs sont dans la base de données. 
Il y a un champ "DOI" dans chaque table (celle des ressources primaires et celle des ressources secondaires).

**Comment by EdouardSombie** [comment]
Oui, je m'en occupe la semaine prochaine.
