### ISSUE TITLE
Déplier ou replier la présentation du corpus par une indication dans l'URL

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#195]
affichage de l’**intro de la page langue** (en 'repliant' la suite) ou de **la page langue en entier** (tout déplié) dans la page « corpus » (ex https://pangloss.cnrs.fr/corpus/Abzakh?lang=en&mode=pro)

Nouvelle option : mettre dans l’url l’info qui permette d’avoir la page qui affiche la page langue en entier ou qui affiche uniquement l’intro. 

Tel que : `seemore=true` ou `seemore=false`

ex. : 
`https://pangloss.cnrs.fr/corpus/Abzakh?lang=en&mode=pro&seemore=true `
ou 
`https://pangloss.cnrs.fr/corpus/Abzakh?lang=en&mode=pro&seemore=false `

**Comment by EdouardSombie** [comment]
C'est bon !
