### ISSUE TITLE
Problème affichage de titre

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#197]
Certains titres de ressources ne s'affichent pas (lorsqu'ils sont ni en anglais ni en français).

ex : https://pangloss.cnrs.fr/corpus/show?corpus=Khroskyabs&lang=fr&mode=pro&oai_primary=cocoon-4ecce7d8-6aac-4776-8ce7-d86aac77767e&oai_secondary=cocoon-13d50e3c-7280-4a70-950e-3c72804a7058

Ici le titre est en chinois (pas écriture chinoise mais du chinois quand même) et il n'y a pas d'autre titre.
Il faudrait afficher le titre quelle que soit sa langue si jamais il n'y a pas de titre en français ou en anglais.

**Comment by sguillaume** [comment]
J'ajoute les 2èmes titres pour chaque ressource donc un titre va s'afficher mais il faut résoudre tout de même le problème car souvent il n'y a pas de 2ème titre.

**Comment by sguillaume** [comment]
Demander au déposant d'indiquer au minimum un titre en anglais ou en français

**Comment by alexis-michaud** [comment]
> Demander au déposant d'indiquer au minimum un titre en anglais ou en français

À reporter dans une doc' à destination des déposantes ?
