### ISSUE TITLE
Affichage des dates "période"

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#198]
Nous n'avons pas pris en compte tous les types de dates à l'affichage sur le site. (partie droite de la page, côté métadonnées)
En général la date d'enregistrement de la ressource est sous la forme : 2021-08-09
Mais parfois, la date n'est pas une date précise mais une période. Dans ces cas là ça se présente sous cette forme : start=1950; end=1955;
Il faudrait à l'affichage que ça se transforme en : 1950-1955

ex : https://pangloss.cnrs.fr/corpus/show?continuousPlay=false&corpus=Korandje&lang=fr&mode=pro&oai_primary=cocoon-64016710-c282-4d79-8167-10c2823d7935&oai_secondary=cocoon-b59b88f7-5577-4a26-9b88-f75577aa2681

**Comment by alexis-michaud** [comment]
En lien avec la saisie des dates dans Eastling lors de la création de ressources : @m8nli9ht
