### ISSUE TITLE
Afficher le contenu de l'attribut who

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#199]
Il faudrait afficher le contenu de l'attribut "who" du xml afin d'indiquer qui parle dans les transcriptions (quand il est indiqué).

exemple : 
< S id="S1" who="Da'a" >
< FORM >han-nuu-dɛso dɛ< /FORM >
<TRANSL xml:lang="fr">C’est l’histoire d’une femme < /TRANSL >
< /S >

Peut être devant la transcription mettre **Da'a :** en gras.

**Da'a :** han-nuu-dɛso dɛ

**Comment by m8nli9ht** [comment]
Je vois l'idée, l'attribut who est-il au niveau d'un élément S seulement ou aussi W ?

**Comment by sguillaume** [comment]
Uniquement au niveau de S

**Comment by m8nli9ht** [comment]
@sguillaume pourrais-tu me donner les identifiants oai de ressources de cet exemple ?

**Comment by alexis-michaud** [comment]
oai:crdo.vjf.cnrs.fr:cocoon-9c3f6e3f-8d2b-4cba-bf6e-3f8d2b5cbac5

Pour info : On peut retrouver un document

**Comment by sguillaume** [comment]
Voilà un exemple avec l'attribut who :
https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-b117ee60-1bba-3baf-b375-052cbf5bc305&oai_secondary=cocoon-2328d26e-c0a8-316c-8926-668c94bc2555

**Comment by m8nli9ht** [comment]
Je pense qu'on peut déplacer ce ticket dans le repo de Eastling Player

**Comment by m8nli9ht** [comment]
Où faut-il afficher cette info : 
1/Devant la transcription ?
2/Devant la traduction ?
3/Devant les 2 ?

**Comment by sguillaume** [comment]
Devant la transcription ça suffit je pense non ?

Un exemple sur un site qu'on avait développé pour une ANR : http://epopee.huma-num.fr/tools/show_text.php?id=cocoon-b117ee60-1bba-3baf-b375-052cbf5bc305

Mais en gras ça serait mieux.

**Comment by m8nli9ht** [comment]
Parfait, je livre cet ajout avant la fin de semaine

Le mar. 29 nov. 2022 à 14:18, sguillaume ***@***.***> a
écrit :

**Comment by m8nli9ht** [comment]
Pour test et validation :
https://pangloss-dev.huma-num.fr/corpus/show?continuousPlay=false&lang=en&mode=pro&oai_primary=cocoon-b117ee60-1bba-3baf-b375-052cbf5bc305&oai_secondary=cocoon-2328d26e-c0a8-316c-8926-668c94bc2555&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono%2Bother&optionSentenceTranslations=en&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=other&optionWordTranslations=

**Comment by sguillaume** [comment]
Bon, je n'ai peut être pas trop de talent pour l'esthétique.
C'est pas super lisible mon idée non ?

Bon en tout cas l'info est là et c'est le principal !

Dans une autre couleur sinon ?
Ou autre ?

**Comment by m8nli9ht** [comment]
J'ai livré en prod, comme ça l'info apparaît déjà. Pour le côté esthétique, plutôt demander l'avis de @EdouardSombie !

**Comment by sguillaume** [comment]
Merci beaucoup !

**Comment by alexis-michaud** [comment]
Oui, et aussi éviter de rajouter un préfixe `: ` à tous les textes qui n'ont pas d'attribut `who` et se retrouvent maintenant décorés avec deux points en début de chaque phrase :)
![image](https://user-images.githubusercontent.com/6072524/205459576-f887cdd2-edc0-417d-9bf5-deeb32672542.png)

**Comment by alexis-michaud** [comment]
:wave: @EdouardSombie pour rappel, le souci du préfixe ":" inutile est toujours présent (cf commentaire précédent)
Merci bcp et à+

**Comment by sguillaume** [comment]
Ca n'a plus l'air de fonctionner.
L'indication de qui parle n'est plus là même quand c'est indiqué dans le xml d'annotations (ex : https://doi.org/10.24397/pangloss-0008201).
Comme si il y avait eu un retour arrière sur le site.

**Comment by m8nli9ht** [comment]
ok je regarde !

**Comment by m8nli9ht** [comment]
Corrigé, livré
