### ISSUE TITLE
Le bouton "Lecture" ne s'affiche pas pour certains documents

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#200]
Pour les documents nouvellement déposés [en langue boomu](https://pangloss.cnrs.fr/corpus/Boomu), le bouton "Lecture" ne s'affiche pas.
Exemple pour [ce document](https://doi.org/10.24397/pangloss-0008101) : 
![image](https://user-images.githubusercontent.com/6072524/203067405-7a4b2ade-a15a-49f2-848b-b8d8302d6372.png)

(Ni en mode 'pro', ni en 'non pro'.)

En revanche, le bouton s'affiche bien pour des documents d'autres langues : au hasard, le na de Yongning ([ici](https://doi.org/10.24397/pangloss-0004342)).
![image](https://user-images.githubusercontent.com/6072524/203067688-9494e9bc-3d8c-4102-ab6a-2cd4db39d746.png)

C'est bien le diable !?

**Comment by sguillaume** [comment]
C'est a priori normal.
Quand un texte n'est pas synchronisé au niveau de la phrase alors le bouton lecture de la phrase n'apparait pas car il n'y a pas de time code qui permettrait de lancer la lecture.

**Comment by alexis-michaud** [comment]
Ah pardon ! je comprends
Merci bcp @sguillaume !
