### ISSUE TITLE
Affichage png et distinction image synchronisée (à intégrer au xml) et image seule

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#201]
Modification du site pour permettre l'affichage d'images (png ou jpeg) de type image (ex.partitions de musique ou photos) VS images (png ou jpeg) de type texte (manuscrits synchronisé avec le xml).

Dans la BDD : 
champ "format" et "type" utilisés.

"format"  -> "type" : 

RESSOURCES SECONDAIRES : 
"text" -> "text" (xml ou texte)
"text" -> "image" (jpeg ou png synchronisés avec le xml d'annotations. ex les abeilles)
"text" -> "pdf" (pdf)
"image" -> "image" (jpeg ou png. ex partitions de musique ou photos)
"dataset" -> "egg" (egg)

RESSOURCES PRIMAIRES : 
"audio" -> type du discours tel que "narrative", "dialogue" etc
"video" -> type du discours tel que "narrative", "dialogue" etc

**Comment by alexis-michaud** [comment]
@EdouardSombie à toi de jouer ?
