### ISSUE TITLE
Case à cocher à supprimer au dessus de chaque phrase

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#205]
Il faudrait supprimer les cases à cocher qui s'affichent au dessus de chaque phrase quand on consulte une annotation xml.
L'idée serait de n'afficher ces cases que quand les gens veulent faire un export.

**Comment by m8nli9ht** [comment]
Ok c'est fait (oubli de ma part : elle est utilisée en dev  - en cours pour les exports)

**Comment by sguillaume** [comment]
Merci !
