### ISSUE TITLE
erreur géolocalisation Boomu

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#208]
![image](https://user-images.githubusercontent.com/6072524/228887835-1bfe0d82-8984-48e9-bf4b-e953ad04abc7.png)
Lat: 27.6767 / long: 100.8507
La langue apparaît comme voisine du na de Yongning :)
(contreforts de l'Himalaya)
![image](https://user-images.githubusercontent.com/6072524/228888601-4c09f666-e0eb-413e-a2f7-bf9483b569ca.png)

alors que c'est une langue d'Afrique.

**Comment by sguillaume** [comment]
Corrigé !
