### ISSUE TITLE
Afficher les différents titres 

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#212]
Il faudrait afficher les différents titres (titres dans différentes langues en général et autres que français et anglais) quelque part dans la page de consultation d'une ressource.
Dans la colonne droite (des métadonnées) ?
En plus petit sous le titre principal ?
Autre ?

**Comment by alexis-michaud** [comment]
En effet, c'est une super-proposition, pour un point important. En particulier quand le titre existe dans la langue en question, ça permet une consultation du document avec son titre. Un titre dans la langue-cible, ça parachève la ressource, en un sens. 

Parmi les choix proposés par @sguillaume : petite préférence pour un affichage dans le même "coin" que le titre principal, plutôt que dans la colonne de droite (colonne des métadonnées). En effet, cette colonne est déjà pas mal remplie ("à la louche" : une quarantaine de lignes, sur mon écran, pour une ressource comme [celle-ci](https://pangloss.cnrs.fr/corpus/show?continuousPlay=false&lang=fr&mode=pro&oai_primary=cocoon-3f7d934e-f69a-49bc-bd93-4ef69ad9bcba&oai_secondary=cocoon-9c3f6e3f-8d2b-4cba-bf6e-3f8d2b5cbac5&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=autre&optionSentenceTranslations=fr&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=)), et d'autre part, au plan typographique le titre a vocation à figurer au-dessus du texte.

En plus petit sous le titre principal : fonctionnellement, ça paraît la chose à faire. On a le titre en français ou en anglais (selon qu'on consulte le site en mode `fra` ou `eng`), le titre "en langue" (langue du document) apparaît dessous, et tout est clair. Mais symboliquement ça ne va pas complètement de soi, de mettre la langue "rare" en plus petit que la "grande langue de communication" : c'est toute la problématique des hiérarchies de prestige, que justement la collection Pangloss "subvertit" à sa façon en mettant en vedette les langues rares. 

Est-ce qu'une typographie "par concaténation", dans un même paragraphe, conviendrait ? Comme ceci : 
<titre dans la langue de consultation> / <titre dans la langue rare concernée> / <titre dans une autre langue> 

Ou regrouper les 2 premiers et mettre les suivants (s'il y en a) en plus petit ?

Il faudra forcément faire un choix à un moment concernant le nombre max de titres. Afin de ne pas nuire à la lisibilité de la page. Limiter à 3 titres en tout ? Ou mettre les titres à partir du 3e en typographie plus petite ? 

Limiter à 3 titres, ça pourrait être "bloquant" pour la personne qui souhaiterait éventuellement avoir un 4e titre. Par exemple, pour une langue du Caucase, on pourrait imaginer d'avoir
- titre en français ou anglais en premier
- titre "en langue" (par exemple : tcherkesse)
- titre en turc (langue nationale)
- titre en russe (langue "incontournable" pour les études caucasiques)

Ca donnerait par exemple ceci, pour un document tcherkesse
![image](https://user-images.githubusercontent.com/6072524/232985495-7cd6dd08-0f8a-4f3e-8117-bc0c077baaa4.png)
[titres 2, 3 et 4 bricolés pour l'exemple, au mépris de la déontologie linguistique la plus élémentaire : prière d'être indulgent]

Encore une question : est-ce que cette fonctionnalité serait exclusivement pour le mode PRO, ou pour les deux modes ?
Les PRO ont l'habitude de jongler avec les langues (et y trouvent du plaisir). Tandis qu'un affichage pléthorique de langues diverses & variées, sans explications, pourrait déconcerter certains membres du public. 

D'un autre côté, il faut encourager les usagers du mode non-PRO qui sont locuteurs de la langue concernée / habitent dans la région où la langue est (ou était) parlée : usagers pour qui l'emploi de la langue-cible, et de langues nationales/régionales de cette région, seront des repères bienvenus.
Première intuition (qui vaut ce qu'elle vaut) : **la fonctionnalité "multi-titres" serait bienvenue pour les deux modes, de façon non différenciée**.
 
Pour satisfaire les visiteurs curieux qui se demandent ce que représentent tels ou tels signes "cabalistiques" (alphabets & langues inconnus), faut-il ajouter le nom de la langue ? 
![image](https://user-images.githubusercontent.com/6072524/232989148-63908b7e-f975-4802-b7ee-91c44728d1b0.png)

ou un code langue ? 
![image](https://user-images.githubusercontent.com/6072524/232988969-3f76d65d-286f-4a4b-9346-0f14b580c48f.png)

Ca représente encore du temps et des efforts de développement & maintenance, et peut avoir l'effet inverse de celui escompté : rebuter les visiteurs non-PRO, qui trouveront tout cet encodage trop "barbelé", et aussi susciter des controverses au sujet des étiquettes de langues ([sujet super-sensible et délicat](https://dlc.hypotheses.org/610)).

**Comment by alexis-michaud** [comment]
Choix effectués en réunion : 
- affichage avec retour à la ligne entre chaque titre (pour tenir compte du cas des titres longs)
- faire suivre le titre du code langue tel que fourni dans les métadonnées du document (pour mémoire : il s'agit d'un code à 2 lettres, ou, en l'absence de code à 2 lettres pour la langue en question, d'un code à 3 lettres). Ce code est fourni en petites majuscules, sur la même ligne (pas de mise en indice).

**Comment by alexis-michaud** [comment]
Super !!
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/1b47d03d-9345-44f7-8f92-ac12d6722216)
:+1:

**Comment by alexis-michaud** [comment]
Ah, j'oubliais de tester avec les ressources dont le titre est monolingue. 

Par exemple pour [celle-ci](https://doi.org/10.24397/pangloss-0008201) : Il n'y a qu'un seul titre, encodé comme étant du français.

![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/dfa038cd-3a12-4b2b-9a79-c536e62d6fd8)

Il faudrait donc afficher cet unique titre, sans y ajouter le code-langue "français".

Dans la version française de l'interface, ça marche bien. 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/cfea007d-8d12-4287-b1b2-5dc351e42f1e)

En revanche, dans la version anglaise, le titre français apparaît deux fois, une fois sans balise langue et une fois avec balise langue (fr).
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/63ead918-270a-4213-b6ea-05a74fe608ad)

**Comment by alexis-michaud** [comment]
Il y a aussi un doublement (non souhaité) du titre quand il n'existe qu'un seul titre **sans balise langue**. 
Par exemple pour [ce document](https://doi.org/10.24397/pangloss-0007807) : 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/76ee0fd2-1d3c-491d-961a-7b0b486a8039)
Dans ce cas de figure-là (qui est répandu), même souci que ci-dessus (à la seule différence qu'il n'y a bien sûr pas de code langue affiché, puisque les métadonnées n'en contiennent pas).

Le rendu à l'affichage est : 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/84837c41-dd64-41a0-b3b2-daef2df689bd)

Solution à mettre en oeuvre : n'afficher qu'un seul titre, sans code langue.

**Comment by alexis-michaud** [comment]
Ou sinon on laisse comme ça pour mettre la pression aux déposant·es : il faut au moins un titre en 2 langues pour un affichage correct, sinon bug garanti :japanese_ogre: :japanese_goblin:

**Comment by EdouardSombie** [comment]
Salut Alexis,
Je n'avais pas en tête la possibilité qu'un titre ne soit rattaché à aucune langue...
J'ai fait en sorte que dans ce cas, il  n'apparaisse pas dans la liste des 'titres alternatifs'.
Dis-moi si ça te va.
A bientôt
Edouard

![Capture d’écran 2023-10-02 à 14 37 53](https://github.com/CNRS-LACITO/Pangloss_website/assets/66474742/ee7ac28f-1d02-4f81-af79-2ec04bcde381)

**Comment by alexis-michaud** [comment]
Bien joué ! 
:+1: 

![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/39a09963-c8f5-4f58-aacc-f75ca614055d)
