### ISSUE TITLE
Modif à faire dans la BDD pangloss

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#214]
Il faudrait mettre dans une table à part toutes les informations concernant la page langue (texte et images).
Pour l'instant ces informations sont dans la table "corpus" et cela concerne les champs "descrpition_html" et "media".

Il faudrait créer une table "description_langue" par exemple qui contiendrait les champs "description_html" et "media".

Ca évitera les suppressions de contenu car ce sont les 2 seuls champs de la table "corpus" qui ne sont pas remplis par le script qui gère cette table.

**Comment by alexis-michaud** [comment]
Info complémentaire fournie par @sguillaume : 
Ca reviendrait à l’on sépare l'information en 2 tables distinctes.
Une qui serait remplie automatiquement et modifiée par les scripts.
L’autre qui serait remplie en ligne ("manuellement") à partir de l’éditeur.

De la sorte, il y aurait 
- une table « corpus » : la table qui existe déjà
- et une table « description_langue » qui contiendrait les champ « description_html » et « media » (qui sont actuellement eux aussi dans la table unique).

**Comment by alexis-michaud** [comment]
Question : créer un identifiant (stable et pérenne, ça va de soi) pour chaque corpus, "une fois pour toutes".
Ajout d'un champ ("clef unique inamovible") qui ne changera jamais (seule modif possible : suppression).
Récupéré en dur (fourni par @sguillaume).

**Comment by alexis-michaud** [comment]
Choix : utiliser le champ `subject`, déjà présent dans les métadonnées.

**Comment by sguillaume** [comment]
Est ce qu'on pourrait mettre une valeur par défaut vide [] dans le champ "media" de la table corpus_description de la BDD ?

Sinon tout est ok !
