### ISSUE TITLE
affichage graphiques statistiques Pangloss sur page "Qui sommes-nous ?"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#216]
Un petit souci pour la page "[Qui sommes-nous ?](https://pangloss.cnrs.fr/qui-sommes-nous?mode=normal)", pour l'affichage de la (vigoureuse) croissance de la collection Pangloss : l'image de droite ("Croissance du nombre de documents" : audio/vidéo et transcriptions) est rognée à gauche et à droite. À droite ce n'est pas gênant. Mais à gauche on perd les indications sur l'axe des ordonnées.

![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/790b9a2e-fe0f-4460-9aea-1026f4c42d35)

(Testé avec Brave et avec Firefox : même résultat. Pour comparaison, l'image d'origine est [ici](https://pangloss.cnrs.fr/uploads/images/other/2022_croissance_nb_docs_w960.png).)

Le code était le suivant : 

```
<div class="image-gallery">
<figure class="image"><img alt="Graphique représentant la croissance du nombre de langues représentées dans la collection Pangloss au fil du temps" height="702" src="https://pangloss.cnrs.fr/uploads/images/other/2023_croissance_nb_langues.png" width="960" />
<figcaption>Croissance de la collection Pangloss : nombre de corpus</figcaption>
</figure>

<figure class="image"><img alt="Graphique représentant la croissance du nombre de documents de la collection Pangloss au fil du temps" height="612" src="https://pangloss.cnrs.fr/uploads/images/other/2022_croissance_nb_docs.png" width="960" />
<figcaption>Croissance de la collection Pangloss : nombre de documents</figcaption>
</figure>
</div>
```

Est-ce qu'il ne vaut pas mieux supprimer les indications de hauteur et largeur, et laisser la feuille de style d'affichage se charger de fixer une taille des images qui convienne à la page? Comme c'est fait par exemple pour les 2 images dans la [page de présentation du corpus na de Yongning (partie en chinois)](https://pangloss.cnrs.fr/corpus/Yongning_Na?mode=pro&seeMore=true&lang=en#%E4%B8%AD%E6%96%87%E4%BB%8B%E7%BB%8D). Les légendes ne sont pas exactement alignées horizontalement, mais c'est peut-être un moindre mal que de voir les images rognées ? 

Le code correspondant est ci-dessous.

```
<div class="image-gallery">
    <figure class="image"><img alt="The Gemu mountain seen from afar" src="https://pangloss.cnrs.fr/uploads/images/languages/na_013pgss.jpg" />
    <figcaption>The Gemu mountain seen from around the hill, above the Yongning monastery (2012).</figcaption>
    </figure>

    <figure class="image"><img alt="The Gemu mountain seen from the village of Alawa" src="https://pangloss.cnrs.fr/uploads/images/languages/na_016pgss.jpg" />
    <figcaption>The Gemu mountain seen from the village of Alawa (2008).</figcaption>
    </figure>
</div>
```

J'ai modifié la page "Qui sommes-nous" (en version française, non-PRO et PRO)... mais l'affichage n'en est pas modifié ! La largeur des images n'est pas ajustée à l'espace disponible : l'image de droite se trouve rognée. Une idée sur la façon de régler ce petit souci ?

(Pour la version anglaise, l'axe des ordonnées est lisible. Mais une fois qu'une solution aura été trouvée pour la page en français, peut-être serait-il néanmoins opportun d'apporter la même retouche pour la version anglaise, ne serait-ce que par cohérence entre les 2 versions linguistiques ?)
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/ae3e2233-9de8-4ca7-b314-7d50800796dd)

**Comment by EdouardSombie** [comment]
Bonjour tout le monde,
Le souci est réglé, les images ne sont plus rognées.
A bientôt
Edouard

**Comment by alexis-michaud** [comment]
Bien joué @EdouardSombie 
:+1:
