### ISSUE TITLE
Ressources avec plusieurs annotations : numérotation erronée dans les boîtes "Identifiants" (ARK, OAI, DOI)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#217]
Pour "[Les abeilles entrent dans la maison](https://pangloss.cnrs.fr/corpus/show?continuousPlay=false&lang=fr&mode=pro&oai_primary=cocoon-861c4050-8ef0-3821-bbbc-a535860ed807&oai_secondary=cocoon-3f8d23d3-424b-3cc4-9970-2be0f4ad92ca&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono&optionSentenceTranslations=en&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=)", il y a 2 annotations : 
- le fichier XML d'annotations
- un fichier JPG : photo du manuscrit lu.

La première est appelée "Annotation 1", et la deuxième "Annotation 2".
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/47343f77-6512-44a0-967e-4e4c38433dfb)

Mais dans les boîtes "Identifiants" (ARK, OAI, DOI), un peu plus bas dans le volet de droite, les deux apparaissent sous le même intitulé : "Annotation 1".
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/06b021e3-ba9c-44d1-85f7-84ae78cbe45e)

@EdouardSombie il y a un bug à corriger dans le code pour l'affichage des identifiants, n'est-ce pas ? Pour traiter le cas dans lequel il y a plusieurs fichiers qui sont dans la même catégorie de l'ontologie Pangloss / Cocoon.

**Comment by EdouardSombie** [comment]
C'est fait :)

**Comment by alexis-michaud** [comment]
Bien joué :+1:
