### ISSUE TITLE
ajouter le champ "date" dans la liste des ressources d'une langue

### ISSUE THREAD

**Issue by maxime-fily** [CNRS-LACITO/Pangloss_website#220]
Lorsque je consulte les ressources, souvent j'essaie de retrouver un enregistrement dont j'avais noté la date. Serait-il possible, pour faciliter la navigation, que la date de l'enregistrement soit affichée sur la page ressources d'une langue ? Si cela devait surcharger l'affichage alors il ne fait pas le faire, mais si cela vous semble possible, cela me rendrait de bons services.
![Capture d’écran du 2023-10-11 10-51-12](https://github.com/CNRS-LACITO/Pangloss_website/assets/66940051/2d7c8b17-ef91-42be-b1c4-4962d5bc2987)

**Comment by alexis-michaud** [comment]
Voici le lien vers la page en question : 
https://pangloss.cnrs.fr/corpus/Yongning_Na
L'espace en blanc à droite, c'est la colonne qui contient les infos concernant la langue, et les photos s'il y en a.
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/6f01c11b-8e06-448d-bc78-a0fdbd58d78e)
Une possibilité pour faire de la place afin d'élargir le tableau qui contient la liste des ressources consisterait à utiliser la même stratégie que pour la page de consultation d'une ressource : un bouton "pleine largeur".
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/7df7bdbc-a576-4bf7-b7d2-0719e8076c13)
Ca demanderait un développement supplémentaire, mais ça donnerait en effet un vrai confort pour "jouer" avec la liste des ressources, dont l'affichage pourrait être enrichi de colonnes supplémentaires.

**Comment by alexis-michaud** [comment]
À discuter, @sguillaume @EdouardSombie ?

**Comment by EdouardSombie** [comment]
On fait quoi de ce ticket ?

**Comment by alexis-michaud** [comment]
@EdouardSombie bonne question ! 

Réponse : de mémoire, @sguillaume soulignait qu'il y a en effet des améliorations souhaitables ; du coup la balle est dans le camp de l'équipe Pangloss (autour de @sguillaume) pour définir de façon précise l'ensemble des modifs souhaitées pour la liste des ressources d'une langue, afin que ça soit mis en chantier de façon bien systématique, pas des modifs ponctuelles au compte-gouttes.

**Comment by EdouardSombie** [comment]
J'ai ajouté la colonne date dans le tableau des ressources.

**Comment by sguillaume** [comment]
Parfait ! Merci beaucoup !

**Comment by maxime-fily** [comment]
Bonjour,
Sauf erreur de ma part, la date ajoutée est la date d'ajout, or ce qui importe vraiment est la date de l'enregistrement. Serait-il possible de mettre la **date d'enregistrement** fournie dans les métadonnées plutôt que la date d'ajout ?

**Comment by sguillaume** [comment]
C'est effectivement la date de dépôt d'un enregistrement qui est affichée et non la date de création d'un enregistrement (il y a apparemment eu confusion avec le sens du terme "date de l'enregistrement" car nous avons aussi eu des demandes d'affichages de la date de dépôt de l'enregistrement). 

Etant donné qu'on ne peut pas afficher les 2, je propose qu'on indique effectivement plutôt la date de création de l'enregistrement (elle a l'avantage de permettre de situer la création des enregistrements dans le temps et pourrait être plus utile qu'une date de mise en ligne).

**Comment by maxime-fily** [comment]
Bonjour,
Merci en tout cas, @EdouardSombie d'avoir introduit la colonne. S'il est possible de changer le contenu actuel par la date de l'enregistrement, ce serait super. 
Exemple de balise pour la date de création de l'enregistrement : *<dcterms:created xsi:type="dcterms:W3CDTF">aaaa-mm-jj</dcterms:created>*

**Comment by sguillaume** [comment]
Fait !

**Comment by maxime-fily** [comment]
Merci beaucoup ! Je valide, les dates sont bonnes.
A bientôt,

Maxime
