### ISSUE TITLE
Modification affichage code langue d'un titre

### ISSUE THREAD

**Issue by sguillaume** [CNRS-LACITO/Pangloss_website#228]
Il faudrait afficher les codes langues d'un titre autrement qu'en petites majuscules car ça n'est pas très lisible apparemment.
On s'était dit qu'en minuscule entre parenthèse ça serait peut être plus compréhensible (plus habituel en tout cas).

ex. [https://doi.org/10.24397/pangloss-0003362](https://doi.org/10.24397/pangloss-0003362)

**La souris, le moineau et le chat
The mouse, the sparrow and the cat EN**

donnerait 

**La souris, le moineau et le chat
The mouse, the sparrow and the cat (en)**

**Comment by alexis-michaud** [comment]
Ah, bizarre bizarre ! Est-ce moi qui suis d'humeur chagrine et querelleuse ? Là je me sens prêt à me battre pour défendre les petites capitales, et en rébellion intense contre la mode des minuscules à toutes les sauces : pas fan du cnrs (je préfère le CNRS), pas envie de m'exprimer en en (alors qu'en EN, surtout en petites capitales, ça va tout de suite mieux)...

Qui est derrière le complot de ce "On" qui préfère les minuscules (mais s'arroge une majuscule, il a pas peur de la contradiction On, on dirait) ? Des noms !
Pour les linguistes, qui fabriquent de la charcuterie linguistique à longueur d'année, les parenthèses évoquent autre chose, pas top pour un code langue...

Tous les goûts sont dans la nature ; peut-être prendre le temps de discuter dans l'équipe et faire des comparatifs typographiques sur écran/papier avant de demander une modif' en production sur le site ?

**Comment by alexis-michaud** [comment]
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/d1c18f98-bdd5-4abf-aeb2-51e6a58d8516)

y'a rien de plus beau au monde pourtant...
Ajouter un espace ou deux de plus avant le code langue en petites capitales ?

**Comment by alexis-michaud** [comment]
Une journée ayant passé, je suis prêt à me rendre aux intuitions convergentes de @sguillaume et @BenjaminGalliot.
Une proposition de @BenjaminGalliot pour éviter des parenthèses consisterait à avoir le code langue dans la marge de gauche (comme le numéro de phrase), peut-être en grisé ("accentuation négative" si j'ai bien retenu la formule de Benjamin).

**Comment by EdouardSombie** [comment]
Salut, je pense que le nom de langue dans la marge risque d'être peu compréhensible.
J'ai coupé la poire en deux : j'ai gardé les majuscules que j'ai mises entre parenthèses, avec un peu plus d'espace avant.
Dites-moi ce que vous en pensez. Moi, je trouve ça pas mal :)

<img width="649" alt="Capture d’écran 2023-12-18 à 16 19 24" src="https://github.com/CNRS-LACITO/Pangloss_website/assets/66474742/2f9884e0-d6b9-46c2-834d-19cc4616308a">

**Comment by sguillaume** [comment]
Moi ça me va !

**Comment by alexis-michaud** [comment]
Bravo les pro ! C'est super-beau. :100:
