### ISSUE TITLE
urgence : site Pangloss en rade : ressources audio non accessibles (blocage côté Cocoon ?)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#234]
Bizarre : les ressources audio non consultables sur le site Pangloss

Ex. : une ressource du carrousel, "[Dog & monkey](https://doi.org/10.24397/pangloss-0008566)", a un audio affiché de... 5 secondes ??
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/d8d0ca8b-1d77-4e8f-85c0-030411cccc0d)

Pourtant il y a 43 phrases, et 1 minute 32 d'audio

Les boutons de commande audio ne répondent pas.

https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-79fabae8-90b3-430e-baba-e890b3330e21&oai_secondary=cocoon-f16904c3-93eb-4cdf-a904-c393ebdcdfd7&lang=fr&mode=normal&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=phono&optionSentenceTranslations=en&optionWordTranscriptions=&optionWordTranslations=&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false

Pareil pour [le na](https://pangloss.cnrs.fr/corpus/show?corpus=Yongning_Na&lang=en&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&mode=normal&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr&optionWordTranscriptions=&optionWordTranslations=&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false)

Il semble que le blocage vienne du fait que les ressources dans Cocoon ne soient pas accessibles : erreur 403 accès interdit

**Comment by alexis-michaud** [comment]
Via le [site Cocoon](https://cocoon.huma-num.fr/exist/crdo/meta/cocoon-64746e47-e29e-36fc-9b81-444433975f36), pas de consultation possible : impossible de lire l'enregistrement audio.
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/7c580d94-3547-4b9d-b076-baf7402cd90e)

Souci au redémarrage après le gros bug sur les services d'hébergement de HAL, Huma-Num & co. ?

**Comment by sguillaume** [comment]
Tout a l'air de fonctionner correctement à nouveau (ou alors j'ai raté quelque chose).
Vu que les ressources sont hébergées sur les serveurs d'Huma-Num, le souci devait effectivement logiquement venir de chez eux.

**Comment by alexis-michaud** [comment]
Désolé de rouvrir le ticket, mais ça ne remarche pas sur mon poste. 
- Toujours pas d'audio disponible via l'interface (consultation en ligne)
- Toujours une erreur 403 qd j'essaie de télécharger la ressource
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/4c388f28-fd5c-4255-8ce3-98ac5a0437f6)

**Comment by alexis-michaud** [comment]
Voici comment l'audio est lié via le site Cocoon : 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/8ce3c2fb-977b-4692-af60-c0a3d743da19)
([voici le lien](https://cocoon.huma-num.fr/data/michaud/crdo-NRU_F4_FUNERAL_CUSTOM.mp3))
et voici le résultat depuis mon poste : 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/7774af00-4f6f-4deb-8429-fedfd6064ad1)

**Comment by alexis-michaud** [comment]
En revanche, le XML s'affiche bien.

Une différence avec ce que j'obtenais hier, c'est que la durée de l'audio ne s'affiche plus à 5 secondes, mais à zéro : 
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/017adbde-e761-469f-8f62-642d50d4b0cb)

**Comment by alexis-michaud** [comment]
Pour moi, ça affecte aussi les autres collections de Cocoon (voici [l'exemple que je viens de tester](https://cocoon.huma-num.fr/exist/crdo/meta/cocoon-7dbbbdc0-2a5d-396f-ba17-93d13f668dc9)).

Ca serait un des intérêts de disposer de statistiques globales de consultation & téléchargement de fichiers pour Cocoon : de repérer quand ça passe à zéro... ? Un moyen (parmi d'autres) de détecter un souci technique ?

**Comment by alexis-michaud** [comment]
Situation inchangée jusqu'à présent : toujours le même message d'erreur pour accéder aux fichiers audio.
![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/b90cc058-1f85-4f71-ba34-83d156820693)

**Comment by sguillaume** [comment]
De mon côté j'ai vu constaté un truc un peu bizarre.
Tout fonctionne lorsque je suis en 4G/5G (lorsque je consulte pangloss ou cocoon sur mon téléphone ou que je me connecte à internet sur mon ordi via mon téléphone) et ça ne marche pas quand j'accède à pangloss ou cocoon via la connexion internet de ma box.
Mais je ne saurai pas expliquer pourquoi.

**Comment by alexis-michaud** [comment]
Les choses sont revenues dans l'ordre, merci à la team Huma-Num :)
Serait-il possible de faire un petit bilan, histoire que ce souci soit clairement identifié et décrit ? Cela permettrait de le reconnaître plus rapidement s'il se reproduisait à l'avenir, voire de le détecter automatiquement par un test automatisé ? (#180)

**Comment by EdouardSombie** [comment]
Salut Séverine,
ça me dit quelque chose, on avait déjà eu ce problème.
De mémoire, cela avait été réglé par les administrateurs du serveur.

**Comment by alexis-michaud** [comment]
@EdouardSombie effectivement, ce sont les administrateurs du serveur (à Huma-Num) qui ont fait le nécessaire. 
Pour la mise en place d'un test pour voir si le site pangloss.cnrs.fr répond bien, par contre, ça serait plutôt à toi & Séverine de concevoir quelque chose, non ?
Spécifiquement, il s'agirait de vérifier que ça répond bien côté fichiers audio : qu'on ne se prend pas une erreur 403 pour l'accès au fichier audio.

**Comment by alexis-michaud** [comment]
(Comme ce souci-ci est réglé, je ferme le ticket... en rappelant encore une fois l'actualité du ticket #180)

**Comment by sguillaume** [comment]
Salut Edouard,
Oui c'est exactement le même souci qu'on a eu la dernière fois. Et mêmes causes !
