### ISSUE TITLE
Mode édition │ Page langues │ Impossible de charger les descriptions de la langue Kibiri

### ISSUE THREAD

**Issue by Balthazar45** [CNRS-LACITO/Pangloss_website#237]
Lors de l'utilisation en mode édition pour saisir les descriptions de la langue Kibiri, réception du message suivant : 

_Impossible de charger les descriptions de cette langue !_

Testé sur deux navigateurs différents.

Brave : 

<img width="834" alt="Capture d’écran 2024-07-11 à 09 36 44" src="https://github.com/CNRS-LACITO/Pangloss_website/assets/53433279/4b7f6991-837e-4c1f-b433-ddf1c4e2adac">

et sur Safari : 

<img width="824" alt="Capture d’écran 2024-07-11 à 09 28 16" src="https://github.com/CNRS-LACITO/Pangloss_website/assets/53433279/548be411-7636-4801-96bd-0f4a9e55e52c">

**Comment by sguillaume** [comment]
Il fallait créer l'entrée pour la langue Kibiri dans la BDD dans la table corpus_description.
C'est fait !
Normalement ça devrait marcher maintenant.

**Comment by Balthazar45** [comment]
Merci !
Everythings is all right !

<img width="1212" alt="Capture d’écran 2024-07-12 à 17 01 59" src="https://github.com/user-attachments/assets/1ee70cd7-cd52-4762-8333-eb80eb977345">
