### ISSUE TITLE
affichage DOI au niveau de la phrase incomplet pour 2 textes récents

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#238]
Globalement, l'affichage des DOI au niveau de la phrase fonctionne, et rend de grands services. :rose: 
Mais pour certaines ressources, l'affichage au niveau de la phrase ne fonctionne pas, et cela en dépit du fait que l'affichage du DOI pour le document entier fonctionne sans problème. 
Sans doute est-ce parce qu'il s'agit de 2 textes récemment déposés, et le problème disparaîtra-t-il de lui-même lors du prochain moissonnage des métadonnées de Cocoon ?
Exemple de [cocoon-a329c1a2-562a-4e1d-a9c1-a2562aee1d78](https://pangloss.cnrs.fr/corpus/show?continuousPlay=false&lang=en&mode=pro&oai_primary=cocoon-9aa889d0-787b-3bcb-bc56-94dadadae7ae&oai_secondary=cocoon-a329c1a2-562a-4e1d-a9c1-a2562aee1d78&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=) : 
![image](https://github.com/user-attachments/assets/0acd87f1-c4bd-481f-b46e-acde11e10a4a)
![image](https://github.com/user-attachments/assets/80732170-2131-4083-a0ed-ed2afd847ed3)

Il s'agit d'un texte dont la transcription a été déposée récemment.

Idem pour [le 2e texte dont la transcription a récemment été déposée](https://pangloss.cnrs.fr/corpus/show?continuousPlay=false&corpus=Yongning_Na&lang=fr&mode=pro&oai_primary=cocoon-1914898a-058e-3801-a440-1d21efeca266&oai_secondary=cocoon-ce56ce81-7cca-42d3-96ce-817cca82d38a&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr%2Bzh&optionTextTranscriptions=&optionTextTranslations=fr&optionWordTranscriptions=&optionWordTranslations=) : 
![image](https://github.com/user-attachments/assets/2755a37b-dde1-4cd1-91f9-31e853c92087)

**Comment by sguillaume** [comment]
C'est bien parce qu'il s'agit d'un dépôt récent.
Les DOIs pour les annotations n'étaient pas encore créés et tu ne voyais donc que le DOI au niveau de l'audio.
Normalement c'est ok maintenant. les DOIs sont créés et intégrés !
