### ISSUE TITLE
site non accessible ? Erreur:SQLSTATE[HY000] [1045]

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#240]
![image](https://github.com/user-attachments/assets/02c55fc8-398c-454b-8ebf-d5322a8d4752)

Erreur:SQLSTATE[HY000] [1045] Access denied for user 'pangloss'@'cchum-kvm-cluster05.huma-num.fr.' (using password: YES)

**Comment by sguillaume** [comment]
J'ai déjà prévenu Edouard pour voir si nous avons quelque chose à faire de notre côté ou si c'est le souci vient d'Huma-Num.

**Comment by sguillaume** [comment]
Huma-Num a répondu et ils ont corrigé le souci.
Le site remarche !
