### ISSUE TITLE
Conversion ELAN > Pangloss pour transcriptions de Katia Chirkova : mise en ligne script

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS-LACITO/Pangloss_website#47]
En cours en septembre 2017 (travail réalisé par  @sguillaume ). 

Prévoir de rendre disponible le script (même s'il n'est pas "généraliste"), à titre d'exemple des conversions réalisées et des outils employés à cette fin.

**Comment by alexis-michaud** [comment]
@sguillaume est-ce que ce ticket peut être fermé (considéré comme traité) ?
Merci bcp

**Comment by sguillaume** [comment]
Oui un script qui converti le format elan au format pangloss est en ligne (mais un plus générique) :    
https://github.com/CNRS-LACITO/Pangloss_scripts/
